feat: add an `hasSize` function
fjebaker/fuzzig pull request #7
Opened 2024-08-14 07:54 UTC by alberic89

2024-08-14 10:38 UTC, fjebaker requested changes

2024-08-14 10:38 UTC, fjebaker commented on src/root.zig
> +        // Check is there is enough memory allocated
```suggestion
        // Check if buffers have sufficient memory for a given haystack and 
        // needle length.
```

2024-08-14 10:38 UTC, fjebaker commented on src/root.zig
> +            }
```suggestion
            return (max_haystack <= self.max_haystack) and (max_needle <= self.max_needle);
```
It's easier just to check the positive case.

2024-08-14 10:38 UTC, fjebaker commented on src/root.zig
> +        pub fn hasSize(self: *Self, max_haystack: usize, max_needle: usize) bool {
```suggestion
        pub fn hasSize(self: *const Self, max_haystack: usize, max_needle: usize) bool {
```
This won't and should not mutate memory, so we mark the pointer as `const`.

2024-08-14 10:38 UTC, fjebaker commented on src/root.zig
> +    pub fn hasSize(self: *Ascii, max_haystack: usize, max_needle: usize) bool {
```suggestion
    // Check if buffers have sufficient memory for a given haystack and 
    // needle length.
    pub fn hasSize(self: *const Ascii, max_haystack: usize, max_needle: usize) bool {
```

2024-08-14 10:38 UTC, fjebaker commented on src/unicode.zig
> +    pub fn hasSize(self: *Unicode, max_haystack: usize, max_needle: usize) bool {
```suggestion
    // Check if buffers have sufficient memory for a given haystack and 
    // needle length.
    pub fn hasSize(self: *const Unicode, max_haystack: usize, max_needle: usize) bool {
```

2024-08-14 10:39 UTC, fjebaker commented
In your previous PR you had some tests that made sure `resize` works. It would be very useful to include those (and similar for `hasSize`) in this PR too.

2024-08-14 11:01 UTC, alberic89 commented
But just a question : is it an error that there is `<` and not `<=` at https://github.com/fjebaker/fuzzig/blob/2c5d606f679ee21bd42ef294f4d0be179f36d288/src/root.zig#L256 ?
It makes `score` fail when there is just the size needed.

2024-08-14 16:07 UTC, fjebaker commented
> is it an error that there is < and not <= at 

Yes that is a mistake. Well spotted! Make sure there's a test that catches it and then I think this will be ready to merge.

2024-08-14 16:10 UTC, fjebaker approved these changes
This is all great! My only suggestion is to add a handful more tests that check that smaller sizes pass, and that larger sizes do indeed fail.

When you're happy, let me know and we can merge.

2024-08-14 16:10 UTC, fjebaker commented on src/root.zig
> +    try std.testing.expect(alg.hasSize(8, 2));
```suggestion
    try std.testing.expect(alg.hasSize(8, 2));
    // larger sizes should fail
    try std.testing.expect(alg.hasSize(8, 3) == false);
    // smaller sizes should be fine
    try std.testing.expect(alg.hasSize(2, 1) == false);
```

2024-08-14 16:15 UTC, alberic89 commented
For me, all is good. We can merge it.

2024-08-15 09:06 UTC, fjebaker approved these changes

2024-08-15 09:06 UTC, merged